version: '3'

services:
  app:
    container_name: app-nest-docker
    image: node:14
    restart: always
    working_dir: /app
    command: bash -c "npm install && npm run start:nodemon"
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
